Fix `NoMethodError`
When `country_codes` is nil, the `list_invalid_properties` method will error with a NoMethodError since you cannot call `#length` on `nil`.

```
request = ::Plaid::LinkTokenCreateRequest.new(products: ['transactions'])
request.valid? # false
request.list_invalid_properties # NoMethodError: undefined method `length' for nil:NilClass
```